name = "Results"
uuid = "a6f57dee-de39-11ea-01ba-9f0f7c89923c"
license = "LGPL-3.0-or-later"
authors = ["Colin Gilgenbach <colin@gilgenbach.net>"]
version = "0.1.0"

[extras]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
